#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 24 12:11:07 2018

@author: acelentano
"""

import tkinter

import openpyxl
wb = openpyxl.load_workbook('ELO.xlsx')
sheet = wb['Player Ratings'] 
    

from tkinter import *     
master = Tk()
Label(master, text="Select tournament players").grid(row=0, sticky=W)
def init(self, master):
    for row in range(2, sheet.max_row + 1):
        sum = 0
        sum += row
        player  = sheet['A' + str(row)].value
    
    self.var = player
    c = Checkbutton(master, text=player, variable=player, command=self.cb)
    c.pack()
    
def cb(self, event):
    print ("variable is", self.var.get())
    
    
   # Checkbutton(master, text=player, variable=player, onvalue=1).grid(row=sum, sticky=W)


#wb = openpyxl.load_workbook('brackets.xlsx')
#sheet = wb['#number of players selected'] 
   
#Button(master, text='Quit', command=master.quit).grid(row=sum+1, sticky=W, pady=4)
Button(master, text='Start tournament', command=openbracket).grid(row=sum+1, sticky=W, pady=4)
mainloop()